# NOTE Github Actions execution environments lack a terminal, needed for
# some integration tests. So we use `script` command to fake a terminal.

name: ci
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.15.x, 1.16.x]
        rootless: ["rootless", ""]
        race: ["-race", ""]
        criu-dev: [false]
        include:
          # Also test against latest criu-dev
          - go-version: 1.16.x
            rootless: ""
            race: ""
            criu-dev: true

    steps:

    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
